apiVersion: weave.works/v1alpha1
kind: ProfileInstallation
metadata:
  creationTimestamp: null
  name: pctl-profile
  namespace: default
spec:
  source:
    branch: main
    path: weaveworks-nginx
    url: https://github.com/weaveworks/profiles-examples
status: {}
