apiVersion: weave.works/v1alpha1
kind: ProfileSubscription
metadata:
  creationTimestamp: null
  name: pctl-profile
  namespace: d65f440b-f1d4-465f-961a-dc167e1c3254
spec:
  branch: local_clone_test
  path: weaveworks-nginx
  profileURL: https://github.com/weaveworks/profiles-examples
status: {}
