apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  creationTimestamp: null
  name: pctl-profile-weaveworks-nginx-nginx-deployment
  namespace: fd80a13e-2ad8-4238-aa66-6770a30325fe
spec:
  interval: 5m0s
  path: /var/folders/gh/m47qw8n917n9gym8n_7ttlsc0000gn/T/pctl_test_install_generate_branch_01144622710/weaveworks-nginx/artifacts/nginx-deployment/nginx/deployment
  prune: true
  sourceRef:
    kind: GitRepository
    name: git-repo-name
    namespace: fd80a13e-2ad8-4238-aa66-6770a30325fe
  targetNamespace: fd80a13e-2ad8-4238-aa66-6770a30325fe
status: {}
